In [2]:
import numpy as np

# NN with input and output lyaer
![](./nn1.png)

In [3]:
X = np.array([1, 2])
X.shape

(2,)

In [9]:
W = np.array([[1, 3, 5], [2, 4, 6]])
W.shape

(2, 3)

In [10]:
Y = np.dot(X, W)
Y.shape

(3,)

# NN with 2 hidden layer
![](./nn2.png)
![](./nn3.png)
![](./nn4.png)
![](./nn5.png)

In [55]:
# Input -> Layer 1
X = np.random.randn(2); print(X)
W1 = np.random.randn(2,3)
B1 = np.arange(3)

A1 = np.dot(X, W1) + B1
A1.shape

[ 1.20025684 -0.00804805]


(3,)

In [51]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Z1 = sigmoid(A1)

print(np.vstack((A1, Z1)))
print(Z1.shape)

[[-0.00574629  1.17524472  1.91372552]
 [ 0.49856343  0.76409171  0.87143711]]
(3,)


![](./nn6.png)

In [58]:
# Layer 1 -> Layer 2
W2 = np.random.randn(3, 2)
B2 = np.random.randn(2)
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)
Z2.shape

(2,)

![](./nn7.png)

In [64]:
# Layer 2 -> Output

W3 = np.random.randn(2,2)
B3 = np.random.randn(2)
A3 = np.dot(Z2, W3) + B3
Y = np.identity(2) @ A3
Y.shape

(2,)

# To summarize

In [69]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def init_network():
    network = {}

    network['W1'] = np.random.randn(2,3)
    network['b1'] = np.random.randn(3)
    network['W2'] = np.random.randn(3, 2)
    network['b2'] = np.random.randn(2)
    network['W3'] = np.random.randn(2,2)
    network['b3'] = np.random.randn(2)

    return network


def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = np.identity(2) @ a3    

    return y


net = init_network()
x = np.random.randn(2)

y = forward(net, x)
y

array([0.89384491, 0.34410442])