In [2]:
import numpy as np

In [5]:
a = np.arange(3) + 1
a

array([1, 2, 3])

In [8]:
exp_a = np.exp(a)
exp_a

array([ 2.71828183,  7.3890561 , 20.08553692])

In [11]:
sum_exp_a = np.sum(exp_a)
sum_exp_a

30.19287485057736

In [14]:
y = exp_a / sum_exp_a
y

array([0.09003057, 0.24472847, 0.66524096])

# Implement Soft max

In [22]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

X = np.arange(3)
softmax(X)

array([0.09003057, 0.24472847, 0.66524096])

In [25]:
X = np.arange(1000, 1003)
softmax(X)

<ipython-input-22-14d739b4855e>:2: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
<ipython-input-22-14d739b4855e>:4: RuntimeWarning: invalid value encountered in true_divide
  y = exp_a / sum_exp_a


array([nan, nan, nan])

In [28]:
a = np.arange(1000, 1003)
np.exp(a) / np.sum(np.exp(a))

<ipython-input-28-a5249fd32b7e>:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
<ipython-input-28-a5249fd32b7e>:2: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [30]:
c = np.max(a)
c

1002

In [33]:
a - c

array([-2, -1,  0])

In [34]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([0.09003057, 0.24472847, 0.66524096])

# Reimplement softmax with fixing overfolow

In [40]:
def softmax(a):
    a -= np.max(a)
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

X = np.arange(1000, 1003)
softmax(X)

array([0.09003057, 0.24472847, 0.66524096])

In [41]:
softmax(X).sum()

0.9999999999999999